server:
  port: 8888
spring:
  application:
    name: guilherme-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Luiz-Guilherme2907/config-server-ms-kotlin
          search-paths:
          - 'greeting-service*'